name: CDK Deployment
run-name: "CDK ${{ inputs.action }} on ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'アクション選択'
        required: true
        type: choice
        options:
          - diff
          - deploy
      environment:
        description: 'デプロイ環境'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - stg
          - prod

permissions:
  id-token: write
  contents: read

jobs:
  cdk:
    name: CDK ${{ inputs.action }} on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './cdk/package-lock.json'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Install dependencies
        working-directory: ./cdk
        run: npm ci

      - name: CDK Diff
        if: inputs.action == 'diff'
        working-directory: ./cdk
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "# CDK Diff Results for ${{ inputs.environment }}" > diff_output.md
          echo "\`\`\`diff" >> diff_output.md
          npx cdk diff --color=never >> diff_output.md 2>&1 || true
          echo "\`\`\`" >> diff_output.md
          cat diff_output.md >> $GITHUB_STEP_SUMMARY

      - name: CDK Deploy
        if: inputs.action == 'deploy'
        working-directory: ./cdk
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "# CDK Deploy Results for ${{ inputs.environment }}" > deploy_output.md
          echo "\`\`\`" >> deploy_output.md
          npx cdk deploy --all --require-approval never 2>&1 | tee -a deploy_output.md
          echo "\`\`\`" >> deploy_output.md
          cat deploy_output.md >> $GITHUB_STEP_SUMMARY